import { StyleSheet, StatusBar } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  nav: {
    marginLeft: 15,
    marginRight: 15,
  },
  acessoRapido: {
    alignItems: 'center',
    marginTop: 10,
    backgroundColor: '#ffffff',
    flexDirection: 'row',
    justifyContent: 'space-between'
  },
  botaoMaisOpcoes: {
    width: 'auto',
    backgroundColor: '#1c1c1e0a',
    borderRadius: 20, 
    paddingBottom: 3,
    paddingLeft: 2,
    paddingRight: 2,
  },
  outrasOpcoes: {    
    fontFamily: 'Inter',
    fontWeight: 900,
    letterSpacing: -1,
    alignContent: 'center',
    justifyContent: 'center',
    fontSize: 16,
    paddingLeft: 6,
    paddingBottom: 9,
    paddingRight: 8,
    paddingTop: 4,
    color: '#000000'
  },
  ladoDireito: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  tirarFoto: {
    fontFamily: 'Inter',
    alignContent: 'center',
    justifyContent: 'center',
    paddingLeft: 10,
    paddingBottom: 10,
    paddingRight: 10,
    paddingTop: 10,
    backgroundColor: '#1c1c1e0a',
    borderRadius: 20,
  },
  botaoAdicionar: {
    width: 'auto',
    backgroundColor: '#4A6CFF',
    borderRadius: 20, 
    paddingBottom: 3,
    paddingLeft: 2,
    paddingRight: 2,
  },
  novo: {
    fontFamily: 'Arial',
    fontWeight: 450,
    alignContent: 'center',
    justifyContent: 'center',
    fontSize: 16,
    paddingLeft: 10,
    paddingBottom: 6,
    paddingRight: 10,
    paddingTop: 6,
    color: '#FFFFFF'
  },
  titulo: {
    color: '#000000',
    fontSize: 32,
    fontFamily: 'Arial',
    fontWeight: 'bold',
    marginTop: 10,
  },
  caixaPesquisa: {
    backgroundColor: '#2c2c2e0a',
    borderRadius: 10,
    padding: 7,
    width: '100%',    
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 7,
    fontFamily: 'Arial',
  },
  lista: {
    flexDirection: 'row',
    marginTop: 15,
    gap: 10,
    width: '100%',
    justifyContent: 'space-between',
    textAlign: 'center',
    marginBottom: 20,
  },
  primeiroItemLista: {
    flexGrow: 1,
    flexShrink: 1,
    backgroundColor: '#F0F3FF',
    padding: 7,
    cursor: 'pointer',
    borderRadius: 20,
    alignItems: 'center',
  },
  itemLista: {
    flexGrow: 1,
    flexShrink: 1,
    backgroundColor: '#2c2c2e0a',
    padding: 7,
    cursor: 'pointer',
    borderRadius: 20,
    alignItems: 'center',
  },
  primeiroTextoLista: {
    color: '#4A6CFF',
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'Arial', 
  },
  textoLista: {
    color: '#00000078',
    fontSize: 12,
    fontWeight: 'bold',
    fontFamily: 'Arial',
  },
  contato: {
    flexDirection: 'row',
    paddingLeft: 30, 
    cursor: 'pointer',
    padding: 5,
  },
  molduraFotoPerfil: {
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: -10,
    marginTop: -10,
  },
  fotoPerfil: {
    width: 50,
    height: 50,
    borderRadius: 25, 
    backgroundColor: 'transparent',
  },
  textoContato: {
    flex: 1,
    marginLeft: 25,
    paddingRight: 15,
    paddingBottom: 15,
    borderBottomWidth: 0.5,
    borderBottomColor: '#eee',
    borderStyle: 'solid',
  },
  linhaNomeHorario: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  nome: {
    color: '#000000',
    fontSize: 15,
    fontFamily: 'Arial',
    fontWeight: 550,

  },
  horario: {
    color: '#787878',
    fontSize: 12,
    fontFamily: 'Arial',
  },
  mensagem: {
    color: '#787878',
    fontSize: 12,
    fontFamily: 'Arial',
    marginTop: 3,
    paddingBottom: 10,
  },
  footer: {
    backgroundColor: '#F2F2F2',
    width: '100%',
    padding: 25,
    borderTopWidth: 0.5,
    borderColor: '#00000023',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 30,
  },
  guiaRapido: {
    flexGrow: 1,
    flexShrink: 1,
    alignItems: 'center',
    cursor: 'pointer',
    marginBottom: 5,
    marginTop: -22,
  },
  textoGuiaRapido: {
    fontSize: 8,
    alignItems: 'center',
    fontFamily: 'Arial',
    color: '#787878',
    fontWeight: 400,
  },
  textoSelecionadoGuiaRapido: {    
    fontSize: 8,
    alignItems: 'center',
    fontFamily: 'Arial',
    color: '#000000',
    fontWeight: 500,
  },
});